version: '3.8'
services:
  backend:
    hostname: backend
    build: ../../awesome-back
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    command: [ "mysqld", "--lower_case_table_names=1", "--innodb-flush-method=fsync" ]
    hostname: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rum-manager
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./init/mariadb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - default
  elasticsearch:
    image: elasticsearch:7.8.0
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - default
  kibana:
    image: kibana:7.8.0
    hostname: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - default
    depends_on:
      - elasticsearch
networks:
  default: {}